### ISSUE TITLE
[CHORE] - Create HSK 1 sample sentences

### ISSUE THREAD

**Issue by TAP327** [TAP327/I_Chinese#8]
Add the first several test characters and test sentences into the SQLite database for HSK 1.

**Comment by NDJSec** [comment]
Duplicate of comment in #4 since it should go here. 
https://github.com/TAP327/I_Chinese/issues/4#issuecomment-2557986484

```
CREATE TABLE "sentence" (
   "id" TEXT,
   "chinese" TEXT,
   "pinyin" TEXT,
   "english" TEXT
)
```

**Comment by NDJSec** [comment]
## Updated Word Table

```
CREATE TABLE "word" (
	"id"	INTEGER,
        "chinese" TEXT, 
	"pinyin"	TEXT,
	"definition"	TEXT,
	"level"	INTEGER,
	"sentences"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
)
```

**Comment by NDJSec** [comment]
The new data has been added and the upload scripts have been fixed. Please take a look at Commit #46281f7 for more information.

**Comment by NDJSec** [comment]
@TAP327 Can we move to close this issue and move full HSK1 to issue #4 instead? This way we remove a duplication of issues.
